### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by baerbock** [CNES/WASP#2]
Dear Mr. Kettig, dear Mr. Hagolle,

I've tried to compile WASP, but encountered an issue.

I'm using ArchLinux and have installed orfeo-toolbox 6.6.1, with header files in /usr/include/OTB-6.6

compiler = gcc 8.3.0 (too new?)

```
[ 90%] Building CXX object UpdateSynthesis/CMakeFiles/otbapp_UpdateSynthesis.dir/src/UpdateSynthesis.cpp.o
In file included from /usr/include/OTB-6.6/otbImageListSource.h:25,
                 from /usr/include/OTB-6.6/otbImageToImageListFilter.h:24,
                 from /usr/include/OTB-6.6/otbVectorImageToImageListFilter.h:24,
                 from /home/papa/aur/_geo/wasp/src/WASP/UpdateSynthesis/src/UpdateSynthesis.cpp:31:
/usr/include/OTB-6.6/otbImageList.h:68:5: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     throw (itk::InvalidRequestedRegionError) override;
     ^~~~~
In file included from /usr/include/OTB-6.6/otbImageList.h:91,
                 from /usr/include/OTB-6.6/otbImageListSource.h:25,
                 from /usr/include/OTB-6.6/otbImageToImageListFilter.h:24,
                 from /usr/include/OTB-6.6/otbVectorImageToImageListFilter.h:24,
                 from /home/papa/aur/_geo/wasp/src/WASP/UpdateSynthesis/src/UpdateSynthesis.cpp:31:
/usr/include/OTB-6.6/otbImageList.txx:53:30: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 ::PropagateRequestedRegion() throw (itk::InvalidRequestedRegionError)
                              ^~~~~
In file included from /usr/include/OTB-6.6/otbPolyLineParametricPathWithValue.h:35,
                 from /usr/include/OTB-6.6/otbPolygon.h:24,
                 from /usr/include/OTB-6.6/otbDataNode.h:25,
                 from /usr/include/OTB-6.6/otbVectorData.h:26,
                 from /usr/include/OTB-6.6/otbWrapperTypes.h:29,
                 from /usr/include/OTB-6.6/otbWrapperApplication.h:26,
                 from /home/papa/aur/_geo/wasp/src/WASP/UpdateSynthesis/src/UpdateSynthesis.cpp:26:
/home/papa/aur/_geo/wasp/src/WASP/UpdateSynthesis/src/UpdateSynthesis.cpp: In member function 'virtual void otb::Wrapper::UpdateSynthesis::DoExecute()':
/usr/include/OTB-6.6/otbMacro.h:57:16: error: expected primary-expression before '<<' token
     itkmsg msg << "\n";                                           \
                ^~
/usr/include/OTB-6.6/otbMacro.h:66:27: note: in expansion of macro 'otbLogMacro'
 #define otbMsgDevMacro(x) otbLogMacro(Debug,otbFileContext(x))
                           ^~~~~~~~~~~
/home/papa/aur/_geo/wasp/src/WASP/UpdateSynthesis/src/UpdateSynthesis.cpp:254:6: note: in expansion of macro 'otbMsgDevMacro'
      otbMsgDevMacro("WARNING: L3A and L2A product sizes differ: " << "L2A: " << nL2AWidth << " " << nL2AHeight << ", "
      ^~~~~~~~~~~~~~
/usr/include/OTB-6.6/otbMacro.h:57:16: error: expected primary-expression before '<<' token
     itkmsg msg << "\n";                                           \
                ^~
/usr/include/OTB-6.6/otbMacro.h:66:27: note: in expansion of macro 'otbLogMacro'
 #define otbMsgDevMacro(x) otbLogMacro(Debug,otbFileContext(x))
                           ^~~~~~~~~~~
/home/papa/aur/_geo/wasp/src/WASP/UpdateSynthesis/src/UpdateSynthesis.cpp:287:6: note: in expansion of macro 'otbMsgDevMacro'
      otbMsgDevMacro("WARNING: L3A and L2A product sizes differ: " << "L2A: " << nL2AWidth << " " << nL2AHeight << ", "
      ^~~~~~~~~~~~~~
make[2]: *** [UpdateSynthesis/CMakeFiles/otbapp_UpdateSynthesis.dir/build.make:63: UpdateSynthesis/CMakeFiles/otbapp_UpdateSynthesis.dir/src/UpdateSynthesis.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1934: UpdateSynthesis/CMakeFiles/otbapp_UpdateSynthesis.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by petket-5** [comment]
Hi,

WASP is currently based on OTB 6.2. You are trying to compile it with OTB 6.6.1, which causes the described compilation errors.

Kind regards,
Peter

**Comment by baerbock** [comment]
@petket-5 OTB 6.2 doesn't compile with current OpenCV.
`opencv_INCLUDE_DIR-NOTFOUND/opencv2/opencv.hpp does not exists.`

Do you have any timeframe for updating WASP?

Kind regards

**Comment by petket-5** [comment]
Hi,

I highly recommend to use the [superbuild of OTB 6.2](https://www.orfeo-toolbox.org/SoftwareGuide/SoftwareGuidech2.html#x16-220002.1.2), which takes care of all dependencies - The provided packages are compatible amongst each other and you won't have to take care of it yourself. 
You can find the necessary superbuild-archives as well as the code under the following link:
https://www.orfeo-toolbox.org/packages/archives/OTB/

Should you still not want to install the superbuild version for one or more constraints, then I would need to know which version of OpenCV you tried using and whether you used the CMAKE_PREFIX_PATH variable to specify the OpenCV directory.

Kind regards,
Peter

**Comment by baerbock** [comment]
Hi Peter,

I think that the superbuild is a handy solution for many people, but not for me.
It's not a static build, but rather an intelligent wrapping. I won't install anything unpackaged and I won't pollute my PATH with something like this:
`export LD_LIBRARY_PATH=~/OTB/install/lib:$LD_LIBRARY_PATH `

What actually makes WASP incompatible to current OTB? If there are only tedious portings I would be glad to help.

Kind regards

**Comment by petket-5** [comment]
Hi,

You don't need to add OTB to your current PATH if you choose to take the standalone version.

Some filters have changed from 6.2 (currently) to 6.4 and then some more on the passage to 6.6, which is why I didn't bother so much changing the version yet. I don't have a complete list of changes to be made though - They will have to be solved in the order they arrive during the compilation.
If you want to try and compile a working WASP version with OTB 6.6, I would very glad. However, please keep in mind that this might be quite a sturdy process. If you need a version of Wasp working right now, then there is no way around OTB 6.2.

Kind regards,
Peter

**Comment by baerbock** [comment]
Hi Peter,

I have actually tried to compile a working WASP version with OTB 6.6 – but it failed with above error.

Your software is well documented, but I'm not a C++ programmer. Which possibly changed OTB filter does `UpdateSynthesis.cpp` use?

**Comment by olivierhagolle** [comment]
Closed, the recommended solution is to use OTB 6.2, and we do not have time to help you porting it with OTB 6.6.
Olivier
