### ISSUE TITLE
Outdated OTB

### ISSUE THREAD

**Issue by tarnh** [CNES/WASP#4]
In a few weeks Orfeo Toolbox 7.0.0 will be released.

The current OTB version is 6.6.2, not 6.2 used by you.

Orfeo Toolbox 6.2 needs several outdated libraries with reported CVEs, so it's becoming a security issue.

Why is CNES itself not using the newest versions of their own tools?

**Comment by olivierhagolle** [comment]
Hi Tarnh,
Changing a component on a working system means: work, issues, validation, corrections, time (much more than the time needed to be polite when rising an issue on github) and money. 
We are a very little team trying to help users handling data.
Regards,
Olivier
