### ISSUE TITLE
Optimal WASP settings over snow and glacier

### ISSUE THREAD

**Issue by FerdinandKlingenberg** [CNES/WASP#8]
Hi,

We notice the WASP L3 Sentinel-2 scene produced over snow and glacier does not have the same quality as over land. Are the any optimal WASP settings you can recommend? Please find the attached images below, L3 date centered around 2020-08-01 
 (image to the left) and the L2 MAJA produced scene have the date 2020-08-02 (image to the right). 
![WASP-L2-34WED](https://user-images.githubusercontent.com/30552443/98551769-faed5600-229d-11eb-902d-bfec4aae9a5c.png)

Could the assist of glacier outline be any help or maybe any product of the "let-it-snow" (I am thinking newer version of WASP)?

Kind regards,
Ferdinand Klingenberg

**Comment by olivierhagolle** [comment]
Hi Ferdinand, 
issues on WASP are very rare (and users too maybe ;)), So i have not set up the mechanism to get an email each time there is a new issue. Sorry for the long awaited answer. 

You are right, is is also something we have observed in the Pyrenees. The assumption behind WASP is that the reflectances change slowly over time. It is of course not the case with snow, for which snowmelt causes a dramatic change. Making a monthly average of snow covered surface at the time of snow melt or snowfall results in artefacts.

We have not yet found a good solution for this.
Best regards,
Olivier

**Comment by FerdinandKlingenberg** [comment]
Dear Olivier,

Thanks a lot for your reply. 
I will close this issue and follow the development at the [Gitlab repository](https://gitlab.orfeo-toolbox.org/remote_modules/wasp). Already following the activity by an RSS :) 

Best regards,
Ferdinand Klingenberg
