### ISSUE TITLE
Possibility of using only the part "Directional Correction"

### ISSUE THREAD

**Issue by safalabolo** [CNES/WASP#9]
Dear petket,
I would need to apply reflectance normalization from Sentinel-2 when acquisitions for the same granule are derived from different relative orbits.
Would there be the possibility of using only a part of the entire package (WASP)?
Thanks in advance for your reply

**Comment by olivierhagolle** [comment]
Hi, we have not yet extracted this module from the others, but you might do it by diving in the code.
Be aware that we are currently implementing a new directional correction, the current one being quite bad for low sun elevations (but OK for SZA lower than 45). @petket-5 do you know if it will be available as a standalone as an OTB app ?
